server:
  port: 10010
spring:
  application:
    name: zephyr-auth
  cloud:
    nacos:
      discovery:
        server-addr: http://1.14.68.75:8848
  redis:
    database: 0
    host: 118.24.169.98
    password:
    port: 6379
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://1.14.68.75:3306/zephyr_sys?autoReconnect=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: qing187

#配置相关
zephyr:
  security:
    code:
      image:
        length: 4
        url: /hello
    oauth2:
      tokenStore: jwt
      clients:
        - clientId: zephyr
          clientSecret: zephyrsecret
#          redirectUris: http://baidu.com
          registeredRedirectUri: 0

