server:
  port: 10020
spring:
  application:
    name: zephyr-sys
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848

# Feign 日志级别
logging:
  level:
    cn.hyqup.sys.api.HelloSysApi: DEBUG

feign:
  sentinel:
    enabled: true
