server:
  port: 10030
spring:
  application:
    name: zephyr-mall
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
logging:
  level:
    cn.hyqup.mall.api.HelloMallApi: DEBUG
feign:
  sentinel:
    enabled: true
